name: Build LD54 for macOS

on:
  push:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake ninja

      - name: Build game
        run: |
          mkdir bin-ci
          cmake -G "Ninja" -S . -B bin-ci
          cd bin-ci
          ninja

      - name: Run install_name_tool
        run: |
          cd bin-ci/LD54.app/Contents/MacOS
          install_name_tool -change @rpath/SDL2.framework/Versions/A/SDL2 ../Frameworks/SDL2.framework/Versions/A/SDL2 LD54
          install_name_tool -change @rpath/SDL2_image.framework/Versions/A/SDL2_image ../Frameworks/SDL2_image.framework/Versions/A/SDL2_image LD54
          install_name_tool -change @rpath/SDL2_mixer.framework/Versions/A/SDL2_mixer ../Frameworks/SDL2_mixer.framework/Versions/A/SDL2_mixer LD54
          install_name_tool -change @rpath/SDL2_ttf.framework/Versions/A/SDL2_ttf ../Frameworks/SDL2_ttf.framework/Versions/A/SDL2_ttf LD54

      - name: Set executable permissions
        run: |
          cd bin-ci/LD54.app/Contents/MacOS
          chmod +x LD54.sh
          chmod +x LD54

      - name : Tar app
        run: tar -cvf LD54.tar -C bin-ci/ --exclude='.DS_Store' LD54.app

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: LD54-macOS
          path: LD54.tar